/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dadada",
        "on-primary-fixed-variant": "#474747",
        "secondary": "#5d5f5f",
        "surface": "#f9f9f9",
        "primary-container": "#1b1b1b",
        "on-tertiary-fixed-variant": "#464747",
        "on-secondary-fixed": "#1a1c1c",
        "inverse-primary": "#c6c6c6",
        "on-surface": "#1a1c1c",
        "surface-container-low": "#f3f3f3",
        "surface-tint": "#5e5e5e",
        "on-error": "#ffffff",
        "on-tertiary-container": "#848484",
        "primary-fixed": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeee",
        "on-secondary-container": "#636565",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#454747",
        "inverse-surface": "#2f3131",
        "on-background": "#1a1c1c",
        "surface-container-high": "#e8e8e8",
        "outline": "#7e7576",
        "primary": "#000000",
        "surface-container-highest": "#e2e2e2",
        "secondary-fixed-dim": "#c6c7c6",
        "on-error-container": "#93000a",
        "background": "#f9f9f9",
        "secondary-fixed": "#e2e3e2",
        "secondary-container": "#e2e3e2",
        "on-primary": "#ffffff",
        "on-primary-container": "#848484",
        "surface-variant": "#e2e2e2",
        "outline-variant": "#cfc4c5",
        "tertiary-fixed": "#e3e2e2",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-fixed-dim": "#c7c6c6",
        "surface-bright": "#f9f9f9",
        "on-primary-fixed": "#1b1b1b",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "on-surface-variant": "#4c4546",
        "on-secondary": "#ffffff",
        "tertiary-container": "#1b1c1c",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#1b1c1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "32px",
        "container-max": "1280px",
        "margin-mobile": "24px",
        "margin-desktop": "64px",
        "unit": "8px",
        "section-gap": "160px"
      },
      fontFamily: {
        "label-caps": ["Montserrat", "sans-serif"],
        "footer-tiny": ["Montserrat", "sans-serif"],
        "display-xl-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-xl": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "footer-tiny": ["10px", { lineHeight: "1.0", fontWeight: "400" }],
        "display-xl-mobile": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-xl": ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
